### ISSUE TITLE
Getting "CryptographyDeprecationWarning: Blowfish has been deprecated" from segments.py.

### ISSUE THREAD

**Issue by jds3d** [kahst/BirdNET-Analyzer#59] opened 2022-09-21 21:54 UTC
When I run segments.py, I get the following warning.  It wouldn't be a big deal except I'm running it with 24 threads and get 12 repetitions of it.  

c:\Users\[user]\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

**Comment by Josef-Haupt** [comment] 2023-02-23 09:58
I can't reproduce this issue on my end. It could be some kind of version mismatch in your packages.
Since this is only a warning I'm closing this issue, perhaps you can manually surpresss the warning with one of the options listed [here](https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings).

**Closed by Josef-Haupt** 2023-02-23 09:58 UTC
