### ISSUE TITLE
Limits to # of Files in a Batch Process

### ISSUE THREAD

**Issue by reedflyfarm** [kahst/BirdNET-Analyzer#368] opened 2024-06-27 23:06 UTC
When I select an input directory (recursive) and use all of the same parameters including the same custom classifier, it appears that there might be a limit to how many files can be processed. None of the files get loaded in to your table. But if I use the same input directory but with less than 100 files, I can load them in to  your table and process. Is there a limit to the # of files in a batch directory?

**Comment by reedflyfarm** [comment] 2024-06-27 23:17
It appears that I had one corrupted .wav file. Would be nice if the UI threw some type of error when trying to load the files. Thanks for considering. And it would be REALLY nice if only one Kaleidoscope.csv file was created so that results could be easily loaded in their UI at one time.

**Comment by Josef-Haupt** [comment] 2024-10-29 10:49
I tried to reproduce the issue with a corrupt file, but I can't reproduce the problem in the current repo.
Also a while back we implemented the possibility to combine any output type into a single file, including kaleidoscope.
I'll close this issue, but if there are further problems please get back to us or create a new issue.

**Closed by Josef-Haupt** 2024-10-29 10:49 UTC
