### ISSUE TITLE
No error reporting for BirdNET-Analyzer_GUI?

### ISSUE THREAD

**Issue by msp2** [kahst/BirdNET-Analyzer#261] opened 2024-02-20 10:55 UTC
When I install the new [BirdNET-Analyzer installer for Windows](https://tuc.cloud/index.php/s/YY3Erjad6ytWYJw), it appears that there is no error reporting when something goes wrong.

For example, if I set up the "Multiple files" tab with "Species selection" set to "Species by location", clicking on the "Analyze" button results in a red "Error" button appearing near the bottom of the UI, but there is otherwise no error reporting:

- No pop up error dialog.
- Clicking on the "Error" button does not result in any error dialog being displayed.
- There is no BirdNET-Analyzer GUI console for error reporting like the one that was displayed for the previous implementation of BirdNET-Analyzer for Windows, which was installed by downloading a zip file rather than a Windows installer.

Screenshot showing BirdNET-Analyzer GUI configuration and red "Error" button at the bottom.

![image (1)](https://github.com/kahst/BirdNET-Analyzer/assets/11218580/e0a90135-a468-4fad-9285-1045b40eb3f4)

Screenshot of the console displayed by previous implementations of BirdNET-Analyzer GUI.

<img width="675" alt="console" src="https://github.com/kahst/BirdNET-Analyzer/assets/11218580/c3bc0650-b1e5-4a9f-9ea4-ece02d6ea5ee">

I believe that the error was triggered by configuring "Species location". It appears that this problem may have been reported previously in:
[Error when using coordinate arguments in analyze.py: 'ValueError: vector too long' #248](https://github.com/kahst/BirdNET-Analyzer/issues/248).

**Comment by Josef-Haupt** [comment] 2024-02-21 12:22
I was able to reproduce the problem on my system.
Looks like there was a version mismatch with the tflite version of the tflite model and the packaged tflite.
It should be fixed in the current installer, if not get back to me.

**Closed by Josef-Haupt** 2024-02-21 12:22 UTC

**Comment by msp2** [comment] 2024-02-21 15:42
Hi Josef,

Thank you! After talking with Stefan yesterday afternoon, I downloaded the new installer and confirmed that BirdNET-Analyzer can run detections with latitude-longitude input. I plan to do more testing today.

-Mike

_________________________________________
Michael Pitzrick (he/his/him)
K. Lisa Yang Center for Conservation Bioacoustics
Cornell Lab of Ornithology, Cornell University
159 Sapsucker Woods Rd
Ithaca, NY 14850
Office: 607-254-2124
Cell: 607-342-5415
